const express = require('express');
const router = express.Router();
const controller = require('./../controllers/viewController');
const booking = require('./../controllers/bookingController');
const authc = require('./../controllers/authController');
router.use(authc.isLoggedin);
router.route('/').get(controller.overview);
router.route('/me').get(controller.me);
router.route('/my_tours').get(booking.myBookings);
router.route('/login').get(controller.login);
router.route('/overview').get(controller.overview);
router.route('/tour/:slug').get(controller.tour);
router.route('/submit-user-data').post(controller.change_data);
module.exports = router;
